_base_: default.yaml
experiment_name: interleaved

training:
  strategy: interleaved
  num_epochs: 10
  batch_type: full
  task_batch_sizes:
    sst: 3
    quora: 64
    sts: 2
  learning_rate: 1.0e-5
