_base_: report_best_self_impl_muon_ftsafe.yaml
experiment_name: report_best_self_impl_muon_ftsafe_20e_plus10

training:
  num_epochs: 10
  init_checkpoint: runs/report_best_self_impl_muon_ftsafe_20e/best.pt
