_base_: report_best_self_impl.yaml
experiment_name: report_best_self_impl_muon20_to_adamw_balanced

training:
  num_epochs: 10
  learning_rate: 3.0e-6
  init_checkpoint: runs/report_best_self_impl_muon_ftsafe_20e/best.pt
  task_loss_weights:
    sst: 0.7
    quora: 1.0
    sts: 1.5
